development:
  adapter: solid_cable
  silence_polling: true

test:
  adapter: solid_cable
  silence_polling: true

production:
  adapter: solid_cable
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: brazilify_production
